export const TILE_SIZE = 16;
export const GRAVITY = 0.5;
export const PLAYER_SPEED = 3;
export const JUMP_VELOCITY = -10;
export const MAX_FALL_SPEED = 12;
export const PLAYER_WIDTH = 14;
export const PLAYER_HEIGHT_SMALL = 16;
export const PLAYER_HEIGHT_BIG = 32;
export const SERVER_TICK_MS = Math.floor(1000 / 60); // ~16ms
export const RESPAWN_INVINCIBILITY_TICKS = 120; // 2 s at 60 Hz
export const STAR_DURATION_TICKS = 600;          // 10 s
export const POWERUP_RESPAWN_TICKS = 1800;        // 30 s
export const SHELL_SPEED = 5;
export const FIREBALL_SPEED = 4;
export const FIREBALL_GRAVITY = 0.2;
export const BULLET_BILL_SPEED = 2;
export const ENEMY_SPEED = 1;
export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 4;
export const LIVES_PER_PLAYER = 3;
export const PIRANHA_VISIBLE_TICKS = 120;
export const PIRANHA_HIDDEN_TICKS = 60;
export const VOTE_DURATION_S = 15;
export const MATCH_END_DELAY_MS = 3000;
